### ISSUE TITLE
ERV in plant

### ISSUE THREAD

**Issue by xiekunwhy** [Tiago-Minuzzi/HamleTE#1]
Hi,

As far as I known, LTR-ERV only appear in animal genome, but I found some LTR-ERV in HamleTE results when classifing plant TEs, is it normal?

Or train models separately according to species class (land plants, animal, fungi ...) may be a good idea to avoid animal specific TEs appear in plant results.

![image](https://github.com/Tiago-Minuzzi/HamleTE/assets/17738229/99ea7dcb-6cbf-4de9-ab7e-becaa7d75065)

Best,
Kun

**Comment by Tiago-Minuzzi** [comment]
Hi, Kun.

Thank you for your question.

You are right. That's a limitation of the labels known by the model, so it classifies to the closest it knows. As HamleTE tries to be a generalist deep learning tool, this may happen. I myself have seen this in other machine/deep learning-based TE classifiers.

Your idea of using animal (or even plant) specific models was considered, but I could not find enough data to train models using this rationale that could get good enough results.

You can try checking the accuracy scores to evaluate if there is another label with a good score and more plausible.

Also, I invite you to try my other tool called TEGym: 
https://github.com/Tiago-Minuzzi/TEGym

Best regards.

Tiago Minuzzi

**Comment by xiekunwhy** [comment]
I am now using DeepTE(https://github.com/LiLabAtVT/DeepTE) in my daily pipeline, which can classify TEs according to species class. Have you compare the performances of HamleTE and DeepTE.

Best,
Kun

**Comment by Tiago-Minuzzi** [comment]
I have tests comparing DeepTE and HamleTE's old version:

![Captura de imagem_20240507_045254](https://github.com/Tiago-Minuzzi/HamleTE/assets/38106815/1fd7b369-249d-4329-8643-8ce443641291)

The figure above show classification metrics for the classification of elements of the Repbase database using the programs EDTA, RepeatMasker, TERL, DeepTE and HamleTE.

I've retrained all models because before HamleTE was too biased for plants, and I want it to be a generalist tool. I still have to redo the tests. Nonetheless, I believe it will perform better than before. I compared the old version of HamleTE and the current one, the latter performed better overall.

DeepTE is a pretty good tool that I use as a reference to improve HamleTE.
